In [ ]:
import librosa
import pandas as pd
import numpy as np
import librosa.display
from matplotlib import pyplot as plt
%matplotlib inline
import os
import csv
# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
#Keras
import keras

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [ ]:
!ls "/content/gdrive/My Drive/Dataset_HVD/"

#Ekstraksi Fitur MFCC

In [ ]:
import librosa
audio_path1 = "/content/gdrive/My Drive/Dataset_HVD/AS/New_AS_001.wav"
audio_path2 = "/content/gdrive/My Drive/Dataset_HVD/MR/New_MR_001.wav"
audio_path3 = "/content/gdrive/My Drive/Dataset_HVD/MVP/New_MVP_001.wav"
audio_path4 = "/content/gdrive/My Drive/Dataset_HVD/MS/New_MS_001.wav"
audio_path5 = "/content/gdrive/My Drive/Dataset_HVD/N/New_N_001.wav"
x1 , sr = librosa.load(audio_path1)
x2 , sr = librosa.load(audio_path2)
x3 , sr = librosa.load(audio_path3)
x4 , sr = librosa.load(audio_path4)
x5 , sr = librosa.load(audio_path5)
audio_path11 = "/content/gdrive/My Drive/Dataset_HVD/AS/New_AS_002.wav"
audio_path21 = "/content/gdrive/My Drive/Dataset_HVD/MR/New_MR_002.wav"
audio_path31 = "/content/gdrive/My Drive/Dataset_HVD/MVP/New_MVP_002.wav"
audio_path41 = "/content/gdrive/My Drive/Dataset_HVD/MS/New_MS_002.wav"
audio_path51 = "/content/gdrive/My Drive/Dataset_HVD/N/New_N_002.wav"
x11 , sr = librosa.load(audio_path11)
x21 , sr = librosa.load(audio_path21)
x31 , sr = librosa.load(audio_path31)
x41 , sr = librosa.load(audio_path41)
x51 , sr = librosa.load(audio_path51)

print(type(x1), type(sr))
print(type(x2), type(sr))

In [ ]:
librosa.load(audio_path1, sr=8000)
librosa.load(audio_path2, sr=8000)
librosa.load(audio_path3, sr=8000)
librosa.load(audio_path4, sr=8000)
librosa.load(audio_path5, sr=8000)

In [ ]:
import IPython.display as ipd
ipd.Audio(audio_path1)#as

In [ ]:
import IPython.display as ipd
ipd.Audio(audio_path2)#MR

In [ ]:
mfccs = librosa.feature.mfcc(x1, sr=sr)
print(mfccs.shape)
#Displaying  the MFCCs:
librosa.display.specshow(mfccs, sr=sr, x_axis='time' ,y_axis='linear')
plt.title('Sinyal AS 1')
plt.colorbar()

In [ ]:
mfccs = librosa.feature.mfcc(x11, sr=sr)
print(mfccs.shape)
#Displaying  the MFCCs:
librosa.display.specshow(mfccs, sr=sr, x_axis='time', y_axis='linear')
plt.title('Sinyal AS 2')
plt.colorbar()

In [ ]:
mfccs = librosa.feature.mfcc(x2, sr=sr)
print(mfccs.shape)
#Displaying  the MFCCs:
librosa.display.specshow(mfccs, sr=sr, x_axis='time', y_axis='linear')
plt.title('Sinyal MR 1')
plt.colorbar()

In [ ]:
mfccs = librosa.feature.mfcc(x21, sr=sr)
print(mfccs.shape)
#Displaying  the MFCCs:
librosa.display.specshow(mfccs, sr=sr, x_axis='time', y_axis='linear')
plt.title('Sinyal MR 2')
plt.colorbar()

In [ ]:
mfccs = librosa.feature.mfcc(x3, sr=sr)
print(mfccs.shape)
#Displaying  the MFCCs:
librosa.display.specshow(mfccs, sr=sr, x_axis='time', y_axis='linear')
plt.title('Sinyal MVP 1')
plt.colorbar()

In [ ]:
mfccs = librosa.feature.mfcc(x31, sr=sr)
print(mfccs.shape)
#Displaying  the MFCCs:
librosa.display.specshow(mfccs, sr=sr, x_axis='time', y_axis='linear')
plt.title('Sinyal MVP 2')
plt.colorbar()

In [ ]:
mfccs = librosa.feature.mfcc(x4, sr=sr)
print(mfccs.shape)
#Displaying  the MFCCs:
librosa.display.specshow(mfccs, sr=sr, x_axis='time', y_axis='linear')
plt.title('Sinyal MS 1')
plt.colorbar()

In [ ]:
mfccs = librosa.feature.mfcc(x41, sr=sr)
print(mfccs.shape)
#Displaying  the MFCCs:
librosa.display.specshow(mfccs, sr=sr, x_axis='time', y_axis='linear')
plt.title('Sinyal MS 2')
plt.colorbar()

In [ ]:
mfccs = librosa.feature.mfcc(x5, sr=sr)
print(mfccs.shape)
#Displaying  the MFCCs:
librosa.display.specshow(mfccs, sr=sr, x_axis='time', y_axis='linear')
plt.title('Sinyal N 1')
plt.colorbar()

In [ ]:
mfccs = librosa.feature.mfcc(x51, sr=sr)
print(mfccs.shape)
#Displaying  the MFCCs:
librosa.display.specshow(mfccs, sr=sr, x_axis='time', y_axis='linear')
plt.title('Sinyal N 2')
plt.colorbar()

#Membuat dataset

ekstraksi fitur kita akan mendapatkan 20 mfcc untuk sampling rate yang diberikan karena dihitung untuk setiap frame sehingga mfcc memiliki 20 kolom.

In [ ]:
header = 'filename'
for i in range(1, 41):
    header += f' mfcc{i}'
header += ' label'
header = header.split()

Membuat dataset CSV

In [ ]:
'''
file = open('data.csv', 'w', newline='')
with file:
    writer = csv.writer(file)
    writer.writerow(header)
genres = 'AS MR MVP N MS'.split()
for g in genres:
    for filename in os.listdir(f'/content/gdrive/My Drive/Dataset_HVD/{g}'):
        songname = f'/content/gdrive/My Drive/Dataset_HVD/{g}/{filename}'
        y, sr = librosa.load(songname, mono=True, duration=3)
        mfcc = librosa.feature.mfcc(y=y, sr=8000)
        to_append = f'{filename}'    
        for e in mfcc:
            to_append += f' {np.mean(e)}'
        to_append += f' {g}'
        file = open('data.csv', 'a', newline='')
        with file:
            writer = csv.writer(file)
            writer.writerow(to_append.split())
'''

In [ ]:
file = open('data.csv', 'w', newline='')
with file:
    writer = csv.writer(file)
    writer.writerow(header)
genres = 'AS MR MS MVP N'.split()
for g in genres:
    for filename in os.listdir(f'/content/gdrive/My Drive/Dataset_HVD/{g}'):
        signal = f'/content/gdrive/My Drive/Dataset_HVD/{g}/{filename}'
        # use kaiser_fast technique for faster extraction
        y, sr = librosa.load(signal, mono=True, res_type='kaiser_fast', sr=8000)
        mfcc = librosa.feature.mfcc(y=y, sr=8000, n_mfcc=40)
        to_append = f'{filename}'  
        for e in mfcc:
            to_append += f' {np.mean(e.T,axis=0)}'
        to_append += f' {g}'
        file = open('data.csv', 'a', newline='')
        with file:
            writer = csv.writer(file)
            writer.writerow(to_append.split())

menghitung semua fitur menggunakan paket librosa dan telah membuat kumpulan data dengan nama file data.csv dan telah memasukkan semua nilai fitur dari Jenis penyakit VHD yang diberikan di header yang diberikan.

Membaca dataset

In [ ]:
data = pd.read_csv('data.csv')
data.head()

filename       mfcc1       mfcc2  ...    mfcc39    mfcc40  label
0  New_AS_001.wav -338.932434  128.745911  ... -1.031902 -0.665413     AS
1  New_AS_002.wav -335.431335  126.407539  ... -0.572627 -0.406498     AS
2  New_AS_003.wav -337.884003  126.753250  ... -1.116142 -0.624152     AS
3  New_AS_004.wav -337.474365  125.737366  ... -1.422316 -1.020553     AS
4  New_AS_005.wav -339.964233  127.570206  ... -1.788425 -1.221795     AS

[5 rows x 42 columns]

Drop data yang tidak berguna dimana "filename" merupakan data yang harus di drop

In [ ]:
# Dropping unneccesary columns
data = data.drop(['filename'],axis=1)
data.head()

mfcc1       mfcc2      mfcc3  ...    mfcc39    mfcc40  label
0 -338.932434  128.745911  69.038406  ... -1.031902 -0.665413     AS
1 -335.431335  126.407539  67.568985  ... -0.572627 -0.406498     AS
2 -337.884003  126.753250  69.803627  ... -1.116142 -0.624152     AS
3 -337.474365  125.737366  69.573746  ... -1.422316 -1.020553     AS
4 -339.964233  127.570206  69.472755  ... -1.788425 -1.221795     AS

[5 rows x 41 columns]

Mengubah jenis penyakit menjadi integer

In [ ]:
genre_list = data.iloc[:, -1]
encoder = LabelEncoder()
y = encoder.fit_transform(genre_list)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 

In [ ]:
#Transforming categorical feature into numeric.
#Goal Keeper = 0
#Defender = 1
#Midfielder = 2
#Forward = 3
#def class_numeric(val):
#    if val == 'AS':
#        return 0
#    elif val == 'MR':
#        return 1
#    elif val == 'MS':
#        return 2
#    elif val == 'MVP':
#        return 3
#    else:
#        return 4
#data['label'] = data['label'].apply(class_numeric)

In [ ]:
#y = data['label']
#print(y)

Semua angka integer merepresentasikan jenis penyakit VHD

In [ ]:
scaler = StandardScaler()
X = scaler.fit_transform(np.array(data.iloc[:, :-1], dtype = float))
#X = data.drop(['label'],axis=1)
print(X)

[[ 1.50559724  0.19330944  0.22373703 ... -0.30944039  0.08614387
   0.35002996]
 [ 1.57522061  0.076081    0.13817654 ... -0.10823342  0.41045802
   0.53740606]
 [ 1.52644651  0.09341235  0.26829379 ... -0.48406773  0.02665881
   0.37989065]
 ...
 [-1.70890806 -0.75462091  0.01576063 ... -0.78521694  0.45935954
   0.74540984]
 [-1.64502697 -0.90098405 -0.22309462 ... -1.41252106 -0.74687892
   1.03828748]
 [-2.05720938 -1.3329276  -0.49126745 ... -0.06952325  0.37926307
   0.21699927]]


Dataset training dan test dibagi menjadi 80:20

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((800, 40), (200, 40), (800,), (200,))

In [ ]:
print(X_test)

[[ 0.71465556  1.06503585 -0.02942162 ... -0.72150431 -1.71751971
  -1.20860695]
 [-0.16228607 -1.11699197 -0.09558973 ... -0.71830656 -1.16536267
  -0.25460847]
 [ 1.55529623  0.46286046 -1.6452803  ... -1.10584907 -0.46594843
  -1.19129674]
 ...
 [ 0.63161596  2.24420718 -1.62468292 ... -0.54954387 -0.1554063
  -0.15214007]
 [ 0.06691502 -1.7712907  -1.1381496  ... -0.93949746 -0.15052419
   0.43189551]
 [-1.37795493  1.32831189  1.3704026  ... -0.1975171  -0.4142302
  -0.27799832]]


In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((800, 40), (200, 40), (800,), (200,))

In [ ]:
def calculate_sensitivity_specificity(y_test, y_pred):
    # Note: More parameters are defined than necessary. 
    # This would allow return of other measures other than sensitivity and specificity
    
    # Get true/false for whether a breach actually occurred
    actual_pos = y_test == 1
    actual_neg = y_test == 0
    
    # Get true and false test (true test match actual, false tests differ from actual)
    true_pos = (y_pred == 1) & (actual_pos)
    false_pos = (y_pred == 1) & (actual_neg)
    true_neg = (y_pred == 0) & (actual_neg)
    false_neg = (y_pred == 0) & (actual_pos)
    
    # Calculate accuracy
    accuracy = np.mean(y_pred == y_test)
    
    # Calculate sensitivity and specificity
    sensitivity = np.sum(true_pos) / np.sum(actual_pos)
    specificity = np.sum(true_neg) / np.sum(actual_neg)
    
    return sensitivity, specificity, accuracy

#Membuat model, testing, dan training

In [ ]:
from keras import models
from keras import layers
model = models.Sequential()
model.add(layers.Dense(256, activation='relu', input_shape=(X_train.shape[1],)))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(5, activation='softmax'))

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
history = model.fit(X_train,
                    y_train,
                    epochs=20,
                    batch_size=128
                    )

Epoch 1/20
7/7 [==============================] - 1s 4ms/step - loss: 1.3218 - accuracy: 0.5638
Epoch 2/20
7/7 [==============================] - 0s 4ms/step - loss: 0.8050 - accuracy: 0.8075
Epoch 3/20
7/7 [==============================] - 0s 4ms/step - loss: 0.5004 - accuracy: 0.8763
Epoch 4/20
7/7 [==============================] - 0s 4ms/step - loss: 0.3364 - accuracy: 0.9050
Epoch 5/20
7/7 [==============================] - 0s 4ms/step - loss: 0.2287 - accuracy: 0.9275
Epoch 6/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1679 - accuracy: 0.9513
Epoch 7/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1242 - accuracy: 0.9638
Epoch 8/20
7/7 [==============================] - 0s 4ms/step - loss: 0.0913 - accuracy: 0.9812
Epoch 9/20
7/7 [==============================] - 0s 5ms/step - loss: 0.0688 - accuracy: 0.9912
Epoch 10/20
7/7 [==============================] - 0s 6ms/step - loss: 0.0514 - accuracy: 0.9950
Epoch 11/20
7/7 [======================

In [ ]:
test_loss, test_acc = model.evaluate(X_test,y_test)
print('test_acc: ',test_acc)

7/7 [==============================] - 0s 2ms/step - loss: 0.0190 - accuracy: 0.9950
test_acc:  0.9950000047683716


Mendapatkan akurasi dengan model yang dapat memprediksi jenis penyakit yang diberikan berdasarkan fitur yang diekstraksi. Model ini mencapai akurasi ...dimana akurasi ini sudah sangat baik

In [ ]:
predictions = model.predict(X_test)
np.argmax(predictions[6])

4

In [ ]:
y_pred = model.predict(X_test).argmax(axis=1)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred,)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred, target_names=['Sinyal AS', 'Sinyal MR','Sinyal MS','Sinyal MVP','Sinyal N'])
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[40  0  0  0  0]
 [ 0 40  0  0  0]
 [ 1  0 39  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 40]]
Classification Report:
              precision    recall  f1-score   support

   Sinyal AS       0.98      1.00      0.99        40
   Sinyal MR       1.00      1.00      1.00        40
   Sinyal MS       1.00      0.97      0.99        40
  Sinyal MVP       1.00      1.00      1.00        40
    Sinyal N       1.00      1.00      1.00        40

    accuracy                           0.99       200
   macro avg       1.00      0.99      0.99       200
weighted avg       1.00      0.99      0.99       200

Accuracy: 0.995


In [ ]:
sensitivity, specificity, accuracy = calculate_sensitivity_specificity(y_test, y_pred)
print ('Sensitivity:', sensitivity)
print ('Specificity:', specificity)
print ('Accuracy:', accuracy)

Sensitivity: 1.0
Specificity: 1.0
Accuracy: 0.995


In [ ]:
lol = X_test[:1]
lil = model.predict(lol)
np.argmax(lil)

2

In [ ]:
y_test[0:100]

array([2, 3, 2, 3, 0, 2, 4, 0, 1, 3, 2, 0, 1, 4, 1, 1, 1, 4, 3, 4, 0, 2,
       3, 1, 2, 1, 4, 0, 4, 3, 3, 2, 3, 3, 3, 2, 2, 0, 4, 2, 3, 1, 1, 3,
       1, 3, 3, 0, 3, 4, 0, 2, 4, 2, 1, 2, 4, 3, 3, 2, 0, 2, 1, 3, 0, 0,
       4, 2, 1, 1, 0, 4, 1, 1, 0, 4, 2, 3, 0, 0, 0, 3, 0, 0, 0, 1, 4, 3,
       4, 4, 3, 0, 4, 3, 2, 4, 0, 3, 1, 3])

In [ ]:
model.save('stetoskopDigital')

INFO:tensorflow:Assets written to: stetoskopDigital/assets


In [ ]:
import tensorflow as tf
# Convert the model.
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the model.
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmpuw3jc6e3/assets


In [ ]:
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the TF Lite model.
with tf.io.gfile.GFile('model.tflite', 'wb') as f:
  f.write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmpg46pt4_t/assets


INFO:tensorflow:Assets written to: /tmp/tmpg46pt4_t/assets


In [ ]:
interpreter = tf.lite.Interpreter('model.tflite')
interpreter.allocate_tensors()

print(interpreter.get_input_details())
print(interpreter.get_output_details())

[{'name': 'serving_default_dense_input:0', 'index': 0, 'shape': array([ 1, 40], dtype=int32), 'shape_signature': array([-1, 40], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'StatefulPartitionedCall:0', 'index': 13, 'shape': array([1, 5], dtype=int32), 'shape_signature': array([-1,  5], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]


In [ ]:
y_test[0].shape

()

#Android Model

#SVM Classifier

##SVM tanpa tuning

In [ ]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear', random_state=0) # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.94


In [ ]:
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred, average='micro'))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred, average='micro'))

Precision: 0.94
Recall: 0.94


In [ ]:
sensitivity, specificity, accuracy = calculate_sensitivity_specificity(y_test, y_pred)
print ('Sensitivity:', sensitivity)
print ('Specificity:', specificity)
print ('Accuracy:', accuracy)

Sensitivity: 0.825
Specificity: 0.975
Accuracy: 0.94


In [ ]:
prediksi = clf.predict(X_train)
print(prediksi)

[1 1 4 4 2 4 1 1 4 3 4 0 3 0 1 3 3 3 2 1 2 4 1 3 4 1 1 2 3 0 3 0 2 0 1 3 1
 4 0 0 4 2 3 0 3 3 1 3 2 2 2 0 1 4 3 1 1 4 2 1 1 3 4 1 3 4 1 1 1 2 0 0 0 0
 2 4 4 3 3 3 0 4 3 0 4 1 0 0 2 4 2 0 1 1 2 0 2 0 4 4 2 1 2 2 2 3 2 0 4 2 2
 0 4 1 0 0 3 1 0 1 1 0 2 0 3 0 3 1 2 0 2 2 0 4 2 0 3 3 0 3 2 4 1 0 0 3 1 3
 4 3 4 0 2 3 3 1 3 1 3 3 2 1 2 1 4 1 2 0 1 2 4 4 1 2 4 4 0 3 1 2 0 0 2 1 3
 2 1 4 4 3 4 0 1 2 4 2 2 2 0 0 2 1 2 3 0 1 2 2 2 4 0 0 3 4 0 1 0 4 0 2 0 0
 4 0 3 0 4 3 2 0 4 0 2 1 2 4 2 4 0 0 1 0 4 1 4 0 3 3 3 1 4 3 1 3 0 3 0 0 1
 0 3 3 4 1 0 1 1 2 2 1 2 0 2 0 3 2 1 1 4 3 1 2 4 2 3 1 1 4 3 3 1 0 1 3 1 3
 0 3 3 0 3 2 1 2 0 4 2 3 4 1 2 0 0 4 3 2 4 1 2 0 3 4 1 0 1 1 3 2 0 4 0 1 4
 3 3 2 4 4 2 1 2 0 1 2 4 3 1 1 3 2 3 3 0 0 3 3 4 3 4 2 0 1 1 3 2 0 3 0 3 4
 2 3 0 2 4 4 4 2 0 2 2 0 1 0 1 4 3 1 1 2 0 3 4 1 2 1 3 1 2 2 1 0 0 3 0 0 0
 4 4 0 1 1 4 1 1 2 4 3 4 4 2 3 2 1 0 0 4 1 1 3 3 4 2 1 3 3 2 3 3 4 4 2 0 1
 2 3 4 2 2 2 4 2 1 3 2 2 3 1 0 4 2 3 3 3 0 0 3 1 0 3 4 0 3 4 0 0 3 2 0 2 3
 0 3 2 2 1 2 4 0 3 4 3 4 

In [ ]:
import pickle
filename = 'svm1.sav'
pickle.dump(clf, open(filename, 'wb'))

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred, target_names=['Sinyal AS', 'Sinyal MR','Sinyal MS','Sinyal MVP','Sinyal N'])
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[39  0  0  1  0]
 [ 6 33  0  1  0]
 [ 1  0 39  0  0]
 [ 0  2  1 37  0]
 [ 0  0  0  0 40]]
Classification Report:
              precision    recall  f1-score   support

   Sinyal AS       0.85      0.97      0.91        40
   Sinyal MR       0.94      0.82      0.88        40
   Sinyal MS       0.97      0.97      0.97        40
  Sinyal MVP       0.95      0.93      0.94        40
    Sinyal N       1.00      1.00      1.00        40

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.94       200
weighted avg       0.94      0.94      0.94       200

Accuracy: 0.94


##SVM TUNING

In [ ]:
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf','linear']} 
  
grid = GridSearchCV(svm.SVC(), param_grid, refit = True, verbose = 10, scoring='accuracy')
  
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.281, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.331, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.1s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.381, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.338, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.325, total=   0.1s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.925, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.969, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.956, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.4s remaining:    0.0s


[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.944, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.919, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.887, total=   0.1s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.856, total=   0.1s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.887, total=   0.1s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................


[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.4s remaining:    0.0s


[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.887, total=   0.1s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.844, total=   0.1s
[CV] C=0.1, gamma=0.1, kernel=linear .................................
[CV] ..... C=0.1, gamma=0.1, kernel=linear, score=0.925, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=linear .................................
[CV] ..... C=0.1, gamma=0.1, kernel=linear, score=0.969, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=linear .................................
[CV] ..... C=0.1, gamma=0.1, kernel=linear, score=0.956, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=linear .................................
[CV] ..... C=0.1, gamma=0.1, kernel=linear, score=0.944, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=linear .................................
[CV] ..... C=0.1, gamma=0.1, kernel=linear, score=0.919, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] .

[Parallel(n_jobs=1)]: Done 250 out of 250 | elapsed:    9.4s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf', 'linear']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=10)

In [ ]:
# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}
SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [ ]:
Dataframe = pd.DataFrame(grid.cv_results_)
Dataframe = Dataframe.drop(['std_test_score','split4_test_score','split3_test_score','split2_test_score','split1_test_score','split0_test_score','params','std_score_time','mean_score_time','std_fit_time','mean_fit_time'],axis=1)
Dataframe.sort_values('rank_test_score', ascending="True")
csvpak = Dataframe.sort_values('rank_test_score', ascending="True")
csvpak.to_csv('datatuning.csv')


In [ ]:
grid_predictions = grid.predict(X_test)

print(confusion_matrix(y_test, grid_predictions))  
# print classification report
print(classification_report(y_test, grid_predictions, target_names=['Sinyal AS', 'Sinyal MR','Sinyal MS','Sinyal MVP','Sinyal N']))
print("Accuracy : ",accuracy_score(y_test, grid_predictions))

[[40  0  0  0  0]
 [ 0 40  0  0  0]
 [ 0  1 39  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 40]]
              precision    recall  f1-score   support

   Sinyal AS       1.00      1.00      1.00        40
   Sinyal MR       0.98      1.00      0.99        40
   Sinyal MS       1.00      0.97      0.99        40
  Sinyal MVP       1.00      1.00      1.00        40
    Sinyal N       1.00      1.00      1.00        40

    accuracy                           0.99       200
   macro avg       1.00      0.99      0.99       200
weighted avg       1.00      0.99      0.99       200

Accuracy :  0.995


In [ ]:
sensitivity, specificity, accuracy = calculate_sensitivity_specificity(y_test, grid_predictions)
print ('Sensitivity:', sensitivity)
print ('Specificity:', specificity)
print ('Accuracy:', accuracy)

Sensitivity: 1.0
Specificity: 1.0
Accuracy: 0.995


#KNN Classifier



```
# This is formatted as code
```

##Jika nilai N=5 (Parameter tuning)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred, target_names=['Sinyal AS', 'Sinyal MR','Sinyal MS','Sinyal MVP','Sinyal N'])
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[39  0  1  0  0]
 [ 2 38  0  0  0]
 [ 1  1 38  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 40]]
Classification Report:
              precision    recall  f1-score   support

   Sinyal AS       0.93      0.97      0.95        40
   Sinyal MR       0.97      0.95      0.96        40
   Sinyal MS       0.97      0.95      0.96        40
  Sinyal MVP       1.00      1.00      1.00        40
    Sinyal N       1.00      1.00      1.00        40

    accuracy                           0.97       200
   macro avg       0.98      0.97      0.98       200
weighted avg       0.98      0.97      0.98       200

Accuracy: 0.975


In [ ]:
sensitivity, specificity, accuracy = calculate_sensitivity_specificity(y_test, y_pred)
print ('Sensitivity:', sensitivity)
print ('Specificity:', specificity)
print ('Accuracy:', accuracy)

Sensitivity: 0.95
Specificity: 0.975
Accuracy: 0.975


## Setelah di Tuning N = ? (Parameter Tuning)

In [ ]:
knn = KNeighborsClassifier()
from sklearn.model_selection import GridSearchCV
k_range = list(range(1, 31))
param_grid = dict(n_neighbors=k_range)
  
# defining parameter range
grid = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy', return_train_score=False,verbose=1)
  
# fitting the model for grid search
grid_search=grid.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 5 folds for each of 30 candidates, totalling 150 fits


[Parallel(n_jobs=1)]: Done 150 out of 150 | elapsed:    2.4s finished


In [ ]:
print(grid.best_params_)

{'n_neighbors': 1}


In [ ]:
y_pred = grid_search.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred, target_names=['Sinyal AS', 'Sinyal MR','Sinyal MS','Sinyal MVP','Sinyal N'])
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[40  0  0  0  0]
 [ 0 40  0  0  0]
 [ 1  0 39  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 40]]
Classification Report:
              precision    recall  f1-score   support

   Sinyal AS       0.98      1.00      0.99        40
   Sinyal MR       1.00      1.00      1.00        40
   Sinyal MS       1.00      0.97      0.99        40
  Sinyal MVP       1.00      1.00      1.00        40
    Sinyal N       1.00      1.00      1.00        40

    accuracy                           0.99       200
   macro avg       1.00      0.99      0.99       200
weighted avg       1.00      0.99      0.99       200

Accuracy: 0.995


In [ ]:
sensitivity, specificity, accuracy = calculate_sensitivity_specificity(y_test, y_pred)
print ('Sensitivity:', sensitivity)
print ('Specificity:', specificity)
print ('Accuracy:', accuracy)

Sensitivity: 1.0
Specificity: 1.0
Accuracy: 0.995


#Random Forest

## Random Forest tanpa tuning

In [ ]:
# Import the model we are using
from sklearn.ensemble import RandomForestClassifier
# Instantiate model with 1000 decision trees
rf = RandomForestClassifier(random_state = 42)
# Train the model on training data
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [ ]:
pred1 = rf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, pred1)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, pred1, target_names=['Sinyal AS', 'Sinyal MR','Sinyal MS','Sinyal MVP','Sinyal N'])
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,pred1)
print("Accuracy:",result2)

Confusion Matrix:
[[40  0  0  0  0]
 [ 1 39  0  0  0]
 [ 0  1 38  0  1]
 [ 0  0  0 40  0]
 [ 0  0  0  0 40]]
Classification Report:
              precision    recall  f1-score   support

   Sinyal AS       0.98      1.00      0.99        40
   Sinyal MR       0.97      0.97      0.97        40
   Sinyal MS       1.00      0.95      0.97        40
  Sinyal MVP       1.00      1.00      1.00        40
    Sinyal N       0.98      1.00      0.99        40

    accuracy                           0.98       200
   macro avg       0.99      0.98      0.98       200
weighted avg       0.99      0.98      0.98       200

Accuracy: 0.985


In [ ]:
sensitivity, specificity, accuracy = calculate_sensitivity_specificity(y_test, pred1)
print ('Sensitivity:', sensitivity)
print ('Specificity:', specificity)
print ('Accuracy:', accuracy)

Sensitivity: 0.975
Specificity: 1.0
Accuracy: 0.985


## Random Forest GridsearchCV Tuning


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(random_state=42)

In [ ]:
param_grid = { 
    'n_estimators': [100 ,200, 500, 300, 400 , 500, 600, 700, 800, 900, 1000],
    #'max_features': ['auto', 'sqrt', 'log2'],
    #'max_depth' : [4,5,6,7,8],
    #'criterion' :['gini', 'entropy']
}

In [ ]:
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5, scoring='accuracy')
CV_rfc.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False, random_state=42,
                                  

In [ ]:
CV_rfc.best_params_

{'n_estimators': 1000}

In [ ]:
#rfc1=RandomForestClassifier(random_state=42, max_features='log2', n_estimators= 200, max_depth=8, criterion='entropy')

In [ ]:
rfc1 = CV_rfc.fit(X_train, y_train)

KeyboardInterrupt: ignored

In [ ]:
pred=rfc1.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, pred, target_names=['Sinyal AS', 'Sinyal MR','Sinyal MS','Sinyal MVP','Sinyal N'])
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,pred)
print("Accuracy:",result2)

In [ ]:
sensitivity, specificity, accuracy = calculate_sensitivity_specificity(y_test, pred)
print ('Sensitivity:', sensitivity)
print ('Specificity:', specificity)
print ('Accuracy:', accuracy)